services:
  app:
    build:
    container_name: python-dev-env
    command: uvicorn entrypoint.main:app --host 0.0.0.0 --port 80 --reload 
    ports:
      - 80:80
    volumes:
        - .:/entrypoint